### ISSUE TITLE
When I start the server, I get this error and I don't know how to fix it.

### ISSUE THREAD

**Issue by Limicrafter** [Super-brawl-team/Obiad-Brawl#2]
![Obiad-Brawl-Error](https://github.com/Super-brawl-team/Obiad-Brawl/assets/139695415/29c1299c-2533-4179-b920-42bcf165a7f9)
When I start the server, I get this error and I don't know how to fix it.

**Comment by Limicrafter** [comment]
I have already installed this.

**Comment by Super-brawl-team** [comment]
You sure you ran this precise command ?
And also if you did pip install crypto, delete it

**Comment by Limicrafter** [comment]
![Obiad-Brawl-Error-2](https://github.com/Super-brawl-team/Obiad-Brawl/assets/139695415/766fc70b-ff33-4f36-9bb0-5ceadfce342e)
It still doesn't work, and I have uninstalled crypto.

**Comment by Super-brawl-team** [comment]
Make sure to have python 3.9

**Comment by Limicrafter** [comment]
Thanks for your help

**Comment by Super-brawl-team** [comment]
So it worked ? Nice! Have a nice brawl

**Comment by Limicrafter** [comment]
Yes it worked👍

**Comment by Super-brawl-team** [comment]
Nice! Dont miss the next BIG update that might come next week 😄!
