### ISSUE TITLE
how to convert a zip into ipa?

### ISSUE THREAD

**Issue by que-pro** [Super-brawl-team/Obiad-Brawl#4]
after i did the previous steps i'm stuck on converting back to .ipa. how can i do that?

**Comment by lokycat** [comment]
rename .zip to .ipa

**Comment by que-pro** [comment]
I tried that but it is still a zip file (i'm on windows 11)

**Comment by lokycat** [comment]
Compress “Payload” and rename “Payload.zip” to “Payload.ipa”. .ipa Is basically a zip folder but with the name .ipa

**Comment by que-pro** [comment]
It hasn't become the ipa file I don't know if renaming works

**Comment by lokycat** [comment]
omg yes it works… delete .zip extension and add .ipa extension… dont do this “Payload.ipa.zip” are you dumb

**Comment by que-pro** [comment]
how do you delete the .zip extension.  I can't figure out how

**Comment by lokycat** [comment]
Are you dumb

**Comment by que-pro** [comment]
ok so the file is just named "Payload" and the type is .zip. If it was an ipa it would have a 3utools icon

**Comment by lokycat** [comment]
Are you dumb? R e n a m e .zip t o .ipa….

**Comment by que-pro** [comment]
Windows doesn't let me

**Comment by lokycat** [comment]
What does it say

**Comment by que-pro** [comment]
There's just no way to change the extention

**Comment by que-pro** [comment]
Not in file manager, not in properties, it will always be a .zip

**Comment by que-pro** [comment]
wait! i just had to change something in my file manager settings
